# syntax documentation
# format: name type mode uid gid
# name is the path to the file you want to create/modify
# type is the type of the file, being one of:
#   f: a regular file
#   d: a directory
#   r: a directory recursively
# mode are the usual permissions settings (only numerical values are allowed)
# name is the path to the file you want to create/modify
opt/bmc/apps/account rd 550 104 104
opt/bmc/apps/account r 440 104 104
etc/rc.d/rc.start/S08init_user.sh f 550 0 0
opt/bmc/luaclib/account/account_core.so f 550 0 104
opt/bmc/luaclib/account/libaccount_core_c.so f 550 0 104
opt/bmc/luaclib/account/iam_core.so f 550 0 103
opt/bmc/luaclib/account/pam_bmc_login.so f 755 0 0
opt/bmc/luaclib/account/pam_bmc_session.so f 755 0 0
opt/bmc/luaclib/account/libuip.so f 755 0 0
usr/lib64/ip_lock.so f 755 0 0