-- Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
--
-- this file licensed under the Mulan PSL v2.
-- You can use this software according to the terms and conditions of the Mulan PSL v2.
-- You may obtain a copy of Mulan PSL v2 at: http://license.coscl.org.cn/MulanPSL2
--
-- THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
-- PURPOSE.
-- See the Mulan PSL v2 for more details.
--
-- Author: auto generate
-- Create: 2025-8-21
-- Description: DO NOT EDIT; Code generated by "orm_classes.lua.mako"
local c_object = require 'mc.orm.object'

local orm_classes = {}

function orm_classes.init(db)
    orm_classes.SessionService = c_object('SessionService')
    orm_classes.Authentication = c_object('Authentication')
    orm_classes.Sessions = c_object('Sessions')
    orm_classes.LDAP = c_object('LDAP')
    orm_classes.LDAPController = c_object('LDAPController')
    orm_classes.Kerberos = c_object('Kerberos')
    orm_classes.RemoteGroupsDB = c_object('RemoteGroupsDB')
    orm_classes.RemoteGroup = c_object('RemoteGroup')
    orm_classes.CertificateAuthentication = c_object('CertificateAuthentication')
end

return orm_classes
